name: Android CI

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  ktlint:
    name: Run ktlint
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Run ktlintCheck
        run: ./gradlew ktlintCheck

  build_bundled:
    name: Build bundled debug apps
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Build debug bundled sample app
        run: ./gradlew :activity-sample:assembleBundledDebug :advanced-sample:assembleBundledDebug :fragment-sample:assembleBundledDebug

  build_unbundled:
    name: Build unbundled debug apps
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Build debug unbundled sample app
        run: ./gradlew :activity-sample:assembleUnbundledDebug :advanced-sample:assembleUnbundledDebug :fragment-sample:assembleUnbundledDebug