name: Android CI

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  ktlint:
    name: Run ktlint
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Run ktlintCheck
        run: ./gradlew ktlintCheck

  build:
    name: Build debug app
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Build debug sample app
        run: ./gradlew :activity-sample:assembleBundledDebug :advanced-sample:assembleBundledDebug :fragment-sample:assembleBundledDebug